# Generated by Django 3.0 on 2019-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_component_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
