# Generated by Django 3.0 on 2019-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190414_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='finish_time',
            field=models.DateField(blank=True, default=None),
        ),
    ]
