# Generated by Django 2.1.7 on 2019-04-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190414_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='learner',
            name='cummulative_CECU',
            field=models.IntegerField(default=0),
        ),
    ]
