# Generated by Django 3.0 on 2019-03-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.Component')),
                ('path', models.CharField(max_length=200)),
            ],
            bases=('system.component',),
        ),
        migrations.CreateModel(
            name='ComponentText',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.Component')),
                ('content', models.TextField()),
            ],
            bases=('system.component',),
        ),
    ]
