# Generated by Django 3.0 on 2019-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20190416_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='finish_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
